#!/usr/bin/env python3

## Description

# The script calculates 16S rRNA Gene density: GCN per 1 megabase.

### Input files

# 1. `-f / --final-gene-stats` -- A TSV file of final per-gene statistics.
#   This is the output of the script `merge_bases_categories_taxonomy.py`
#   Mandatory.
# 2. `-p / --primers-dir` -- A directory with primer annealing modelling results.
#   This is the output of the script `check_primers_mfeprimer.py`.
#   Optional.

### Ouput files
# 1. `-o / --outdir` -- output directory.


import os
from src.rg_tools_time import get_time

print(
    '\n|=== {} STARTING SCRIPT `{}` ===|\n' \
    .format(
        get_time(), os.path.basename(__file__)
    )
)

# == Parse arguments ==

import sys
import argparse

parser = argparse.ArgumentParser()

# Input files

parser.add_argument(
    '-m',
    '--in-replicon-map',
    help='the file `replicon_map.tsv.gz` generated by script `make_replicon_map.py`',
    required=True
)

parser.add_argument(
    '-g',
    '--in-gcn-table',
    help='the file `16S_GCNs.tsv` generated by script `calculate_GCNs.py`',
    required=False
)

# Output files

parser.add_argument(
    '-o',
    '--outfile',
    help='output file',
    required=True
)

args = parser.parse_args()

replicon_map_fpath = os.path.abspath(args.in_replicon_map)
gcn_table_fpath = os.path.abspath(args.in_gcn_table)
outfpath = os.path.abspath(args.outfile)

for fpath in (replicon_map_fpath, gcn_table_fpath,):
    if not os.path.isfile(fpath):
        print(f'Error: file `{fpath}` does not exist!')
        sys.exit(1)
    # end if
# end for

outdir_path = os.path.dirname(outfpath)
if not os.path.isdir(outdir_path):
    os.makedirs(outdir_path)
# end if

# == Import them now ==

import polars as pl


# == Proceed ==


genome_size_df = (
    pl.scan_csv(replicon_map_fpath, separator='\t')
    .group_by('asm_acc')
    .agg(pl.col('seq_len').sum().alias('genome_size'))
    .collect()
)

gcn_df = pl.read_csv(gcn_table_fpath, separator='\t')


density_df = gcn_df.join(
    genome_size_df,
    on='asm_acc',
    how='left'
)

density_df = density_df.with_columns(
    (
        pl.col('16S_rRNA_gcn') / pl.col('genome_size') * 1e6
    ).alias('16S_rRNA_density')
).select(pl.col('asm_acc', '16S_rRNA_density'))

density_df.write_csv(
    outfpath,
    separator='\t',
    include_header=True,
    null_value='NA'
)


print('\n{} -- Completed!'.format(get_time()))
print(outfpath)
print(
    '\n|=== {} EXITTING SCRIPT `{}` ===|\n' \
    .format(
        get_time(), os.path.basename(__file__)
    )
)
